default: &default
  api_key: <%= ENV['OPENAI_API_KEY'] || Rails.application.credentials.dig(:openai, :api_key) %>
  model: gpt-5
  temperature: 0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default